### ISSUE TITLE
I can't submit it!

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/content-page#1]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/55094325/77002311-af162700-6931-11ea-87a5-fb00f5a6a52a.png">

@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab lotsss of people had issues with this one. Try changing out part of your code for this instead:

`    <blockquote class="italic milli push-2">
      <p class="push-0">Believe green buds awaken in the spring,<br>That autumn paints the leaves with somber fire;<br>Believe I held my heart inviolate<br>To lavish on one man my hot desire.</p>
      <footer class="micro not-italic">— <cite class="not-italic">The Song of Bélit</cite></footer>
    </blockquote>`

**Comment by Samirahajiragab** [comment]
It doesn't work :(

Thanks though.

**Comment by muxlowc** [comment]
@Samirahajiragab 

1) remove the "article" tag around all of your P tags, and move it up to before your header (it makes sense to have a header and content within an article!)
2) change your google fonts to this on your html
`  <link href="https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700" rel="stylesheet">`
(google has recently updated their interface and it's messing things up)
3) remove the DIV you currently have around your H2 and blockquote
4) change your h2 to this:
`<h2 class="mega pad-t push-2">1. Conan Joins the Pirates</h2>`
5) All of your quotes inside of you hang-puncs are actually tick marks. You need to put curly quotes : copy/paste those from the context.txt

Then I think there might be a bit more padding you need to play around with

**Comment by Samirahajiragab** [comment]
<img width="508" alt="image" src="https://user-images.githubusercontent.com/55094325/77119249-7434f180-6a0c-11ea-843b-1e042b0c8071.png">

Thanks that really helps, but I still can't submit because of screen 960. if I add padding that changes the other screens. Thanks again I don't I can submit this one.

**Comment by Samirahajiragab** [comment]
It works thank you soo much :)

**Comment by muxlowc** [comment]
@Samirahajiragab can you close this issue if it's resolved? thanks!
